### ISSUE TITLE
Add caching

### ISSUE THREAD

**Issue by Timrael** [Timrael/social_shares#5]
Redis?

**Comment by Chocksy** [comment]
@Timrael i'll try to make a PR for this using redis maybe or some rake cache method because we had to disable the gem last week as twitter was respoding like shit and the timeout solved it but if you add total + twitter together on the page you get a 6 seconds waiting time that is just not good at all.

**Comment by Timrael** [comment]
@Chocksy it will be nice :+1:

**Comment by Chocksy** [comment]
@Timrael i managed to make this PR for this #12 check it out.

**Comment by Timrael** [comment]
Moved to https://github.com/Timrael/social_shares_rails
